this update adds a watchlist

diff --git a/stocklookup b/stocklookup
--- a/stocklookup
+++ b/stocklookup
@@ -9,24 +9,52 @@ elif [[ $1 == "" ]] || [[ $1 == " " ]] || [[ $1 == "-I" ]] || [[ $2 == "-I" ]] |
 		IN="`echo $2 | tr a-z A-Z`"
 		curl -s https://finance.yahoo.com/quote/$IN/ > stock.html
 		INPUT="$IN"
-	elif [[ $2 == "-s" ]]; then
+	elif [[ $2 == "-s" ]]
+	then
 		IN="`echo $3 | tr a-z A-Z`"
         	curl -s https://finance.yahoo.com/quote/$IN/ > stock.html
 		INPUT="$IN"
-        elif [[ $3 == "-s" ]]; then
+        elif [[ $3 == "-s" ]]
+	then
                 IN="`echo $4 | tr a-z A-Z`"
                 curl -s https://finance.yahoo.com/quote/$IN/ > stock.html
                 INPUT="$IN"
-        elif [[ $4 == "-s" ]]; then
+        elif [[ $4 == "-s" ]]
+	then
                 IN="`echo $5 | tr a-z A-Z`"
                 curl -s https://finance.yahoo.com/quote/$IN/ > stock.html
                 INPUT="$IN"
+	elif [[ $1 == "-w" ]]; then
+		c="`cat ~/.git/watchlist.txt | wc -l`"
+		line=0
+		while [[ $line -lt $c]]
+		do
+			line=$((line+1))
+			SLU -s "`tail $line ~/.git/stock-look-up/watchlist.txt`" $2 $3 $4 $5 $6 $7 $8 $9
+		done
+	elif [[ $2 == "-w" ]] || [[ $2 == "-w" ]] || [[ $3 == "-w" ]] || [[ $4 == "-w" ]] || [[ $5 == "-w" ]] || [[ $6 == "-w" ]] || [[ $7 == "-w" ]] || [[ $8 == "-w" ]] || [[ $9 == "-w" ]]; then
+		echo "ERROR: -w option must be first."
+		exit 9
 	else
 		read -p "What stock do you want to look up?:    " INPUT
 		INPUT="`echo $INPUT | tr a-z A-Z`"
         	INPUT2="https://finance.yahoo.com/quote/$INPUT/"
         	curl -s $INPUT2 > stock.html
 	fi
+elif [[ $1 == "-e" ]]; then
+	ED="`cat editor.txt`"
+	if [[ $ED == "vi" ]] || [[ $ED == "vim" ]]; then
+		vi watchlist.txt
+		exit
+	elif [[ $ED == "nano" ]] || [[ $ED == "emacs" ]]; then
+		nano watchlist.txt
+		exit
+	elif [[ $ED == "" ]] || [[ $ED == " " ]]; then
+		echo "ERROR: could not find editor, please fill out editor.txt in your .git/stock-look-up directory."
+		exit 10
+	else
+		echo "ERROR: editor $ED could not be found"
+		exit 10
 else
 	echo "ERROR: Not a valid operander"
 	echo "Use operander --help or -h for more information"
@@ -39,9 +67,9 @@ cat stock2.html | tr "<" "\n" > stock3.html
 grep -F "span class=\"Trsdu(0.3s) Fw(b) Fz(36px) Mb(-4px) D(ib)\" data-reactid=\"32\"" stock3.html > stock4.html
 cat stock4.html | tr ">" "\n" > stock5.html
 IT="`cat stock5.html`"
-grep -F "Real Time Price. Currency " stock2.html > cur.html
+grep -F "Currency " stock2.html > cur.html
 cat cur.html | tr "<" "\n" > cur1.html
-grep -F "Real Time Price. Currency" cur1.html > cur2.html
+grep -F "Currency" cur1.html > cur2.html
 cat cur2.html | tr "Currency" "\n" > cur3.html
 CU="`tail -1 cur3.html`"
 if [[ $IT == "" ]]; then
